server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      database: spring_test

rabbitmq:
  queue:
    person_notification: person_notifications
  routing:
    key:
      person: person_notifications
  exchange:
    default: ""


logging:
  level:
    org.springframework.amqp: DEBUG
